export const emojis = [
  {
    name: 'THUMBS UP SIGN',
    unified: '1F44D',
    non_qualified: null,
    docomo: 'E727',
    au: 'E4F9',
    softbank: 'E00E',
    google: 'FEB97',
    image: '1f44d.png',
    sheet_x: 13,
    sheet_y: 38,
    short_name: '+1',
    short_names: ['+1', 'thumbsup'],
    text: null,
    texts: null,
    category: 'People & Body',
    sort_order: 19,
    added_in: '2.0',
    has_img_apple: true,
    has_img_google: true,
    has_img_twitter: true,
    has_img_facebook: true,
    skin_variations: {
      '1F3FB': {
        unified: '1F44D-1F3FB',
        non_qualified: null,
        image: '1f44d-1f3fb.png',
        sheet_x: 13,
        sheet_y: 39,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FC': {
        unified: '1F44D-1F3FC',
        non_qualified: null,
        image: '1f44d-1f3fc.png',
        sheet_x: 13,
        sheet_y: 40,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FD': {
        unified: '1F44D-1F3FD',
        non_qualified: null,
        image: '1f44d-1f3fd.png',
        sheet_x: 13,
        sheet_y: 41,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FE': {
        unified: '1F44D-1F3FE',
        non_qualified: null,
        image: '1f44d-1f3fe.png',
        sheet_x: 13,
        sheet_y: 42,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FF': {
        unified: '1F44D-1F3FF',
        non_qualified: null,
        image: '1f44d-1f3ff.png',
        sheet_x: 13,
        sheet_y: 43,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
    },
  },
  {
    name: 'THUMBS DOWN SIGN',
    unified: '1F44E',
    non_qualified: null,
    docomo: 'E700',
    au: 'EAD5',
    softbank: 'E421',
    google: 'FEBA0',
    image: '1f44e.png',
    sheet_x: 13,
    sheet_y: 44,
    short_name: '-1',
    short_names: ['-1', 'thumbsdown'],
    text: null,
    texts: null,
    category: 'People & Body',
    sort_order: 20,
    added_in: '2.0',
    has_img_apple: true,
    has_img_google: true,
    has_img_twitter: true,
    has_img_facebook: true,
    skin_variations: {
      '1F3FB': {
        unified: '1F44E-1F3FB',
        non_qualified: null,
        image: '1f44e-1f3fb.png',
        sheet_x: 13,
        sheet_y: 45,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FC': {
        unified: '1F44E-1F3FC',
        non_qualified: null,
        image: '1f44e-1f3fc.png',
        sheet_x: 13,
        sheet_y: 46,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FD': {
        unified: '1F44E-1F3FD',
        non_qualified: null,
        image: '1f44e-1f3fd.png',
        sheet_x: 13,
        sheet_y: 47,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FE': {
        unified: '1F44E-1F3FE',
        non_qualified: null,
        image: '1f44e-1f3fe.png',
        sheet_x: 13,
        sheet_y: 48,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
      '1F3FF': {
        unified: '1F44E-1F3FF',
        non_qualified: null,
        image: '1f44e-1f3ff.png',
        sheet_x: 13,
        sheet_y: 49,
        added_in: '2.0',
        has_img_apple: true,
        has_img_google: true,
        has_img_twitter: true,
        has_img_facebook: true,
      },
    },
  },
];
